# Disable testing
SET(BUILD_TESTING OFF CACHE BOOL "")

# Release build
SET(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

# ParaView Edition
SET(PARAVIEW_BUILD_EDITION "CATALYST_RENDERING" CACHE STRING "")

# Needed release CMake options
SET(BUILD_SHARED_LIBS ON CACHE BOOL "")
SET(ENABLE_ospray ON CACHE BOOL "")
SET(ENABLE_ospraymaterials ON CACHE BOOL "")
SET(ENABLE_paraviewsdk ON CACHE BOOL "")
SET(ENABLE_python ON CACHE BOOL "")
SET(ENABLE_python3 ON CACHE BOOL "")
SET(ENABLE_tbb ON CACHE BOOL "")
